### ISSUE TITLE
issues in training with augmentations

### ISSUE THREAD

**Issue by cs-mshah** [sparkfish/augraphy#212]
There are some augmentations which work while others throw cv2 errors while using augraphy augmentations in training.

Here is what the training loop will do depending on what augmentation is passed to it:
```python
def preprocess(self, img, augment=True, aug='taco'):
        '''aug: augmentation object in case of augraphy augmentation'''
        if augment:
            if aug == 'taco':
                img = self.apply_taco_augmentations(img)
            elif isinstance(aug, AugraphyPipeline):
                img = aug.augment(img)["output"]
            else:
                img = aug(img)
```

this works for `Dithering()`, but when I tried to do the following: it gave different cv2 errors:
`folding = Folding(fold_count=4, p=0.5)`
```
img = self.preprocess(img, True, self.aug)
  File "/home/manan/projects/Easter2/src/data_loader.py", line 110, in preprocess
    img = img/255
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```
meaning the returned image was of None type

 `pageborder = PageBorder(width_range=(5, 10))`

```
File "/home/manan/projects/Easter2/src/data_loader.py", line 188, in getNext
    img = self.preprocess(img, True, self.aug)
  File "/home/manan/projects/Easter2/src/data_loader.py", line 107, in preprocess
    img = aug(img)
  File "/home/manan/anaconda3/lib/python3.7/site-packages/augraphy/augmentations/pageborder.py", line 368, in __call__
    image_output = overlay_builder.build_overlay()
  File "/home/manan/anaconda3/lib/python3.7/site-packages/augraphy/utilities/overlaybuilder.py", line 856, in build_overlay
    xend,
  File "/home/manan/anaconda3/lib/python3.7/site-packages/augraphy/utilities/overlaybuilder.py", line 585, in apply_overlay
    overlay_background = cv2.cvtColor(overlay_background, cv2.COLOR_GRAY2BGR)
cv2.error: OpenCV(4.1.0) ../modules/imgproc/src/color.simd_helpers.hpp:94: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<1>; VDcn = cv::impl::{anonymous}::Set<3, 4>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = (cv::impl::<unnamed>::SizePolicy)2; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Unsupported depth of input image:
>     'VDepth::contains(depth)'
> where
>     'depth' is 6 (CV_64F)
```

**Comment by cs-mshah** [comment]
Also, even when `Dithering()` and `LowInkRandomLines(count_range=(10, 15))` work individually, running their pipeline throws an error:
```python
ink_phase = [
    OneOf([Dithering(), LowInkRandomLines(count_range=(10, 15))])
]
paper_phase = [
]
post_phase = [
]
pipeline = AugraphyPipeline(ink_phase, paper_phase, post_phase)

train(pipeline)

```

```
img.shape=(81, 3, 1650), new_y=74, new_x=2000
applying pipeline
OpenCV(4.1.0) ../modules/imgproc/src/resize.cpp:3361: error: (-215:Assertion failed) !dsize.empty() in function 'resize'
```

**Comment by kwcckw** [comment]
Can you confirm what is your image dimension in code?

Right now Augraphy accepts only image dimension of (x, y) - grayscale or (x, y, 3) - BGR. Other than this, it will facing error because it is not the supported image type.

**Comment by cs-mshah** [comment]
Here are the printed dimensions before and after applying the augmentations (page border in this case). It seems to work for the first few images but fails at one point. Surprising thing is the entire training worked for other LowInkRandomLines individually, but fails for other augmentations like page border and pipelines. 
![image](https://user-images.githubusercontent.com/56499208/205475101-7e86b544-17b1-4bfe-abf4-15bdd22e5cd0.png)

Is the size of the image too large for the augmentation?

**Comment by kwcckw** [comment]
Thanks for the print screen. Right now the issue is due to the `cv2.cvtColor` function doesn't accept float image so it gives error only in certain augmentation with `cv2.cvtColor`. We will include a fix to this issue after this.

**Comment by kwcckw** [comment]
With the latest update, the issue should be resolved. Could you try again and see whether you still facing the error?

**Comment by jboarman** [comment]
I'm closing this now.  Please re-open or open a new issue if needed.
